name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Copy files to dist
        run: |
          mkdir -p dist
          cp -r *.html favicon.png CNAME assets column-options extensions issues json methods options welcomes utils dist/
          VERSION=`git rev-list --count master`
          find dist -type f -exec sed -i "s/v=VERSION/v=$VERSION/g" {} \;

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
